/* ===========================================================
   Reference geography data for the "browse list" curtain menu.

   - `countries` is a near-complete list of the world's countries.
   - `provinces` is each country's first-level regions/states/provinces.
   - `cities` is a short list of well-known cities for that COUNTRY
     as a whole (capital + the biggest/most visited ones). It is not
     mapped to a specific province — matching every city to its exact
     region for every country isn't something that can be done
     reliably here, so the city curtain just shows the country's
     known cities regardless of which province you're currently in.

   Coverage is intentionally uneven: most of Europe and the larger,
   most-visited countries worldwide have real lists, filled in and
   checked against current sources. Many smaller or less-traveled
   countries are left empty — typing a custom name always works
   regardless, for anything missing here.
   =========================================================== */

const GEO_DATA = {
  countries: [
    { name: "Afghanistan", provinces: [] },
    { name: "Albania", provinces: [], cities: ["Tirana", "Sarandë", "Berat", "Shkodër", "Vlorë"] },
    { name: "Algeria", provinces: [] },
    { name: "Andorra", provinces: [] },
    { name: "Angola", provinces: [] },
    { name: "Antigua and Barbuda", provinces: [] },
    { name: "Argentina", provinces: ["Buenos Aires Province", "Catamarca", "Chaco", "Chubut", "Córdoba", "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza", "Misiones", "Neuquén", "Río Negro", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fe", "Santiago del Estero", "Tierra del Fuego", "Tucumán", "Ciudad Autónoma de Buenos Aires"], cities: ["Buenos Aires", "Mendoza", "Bariloche", "Ushuaia", "Córdoba", "Salta"] },
    { name: "Armenia", provinces: [] },
    { name: "Australia", provinces: ["New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia", "Tasmania", "Australian Capital Territory", "Northern Territory"], cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Cairns", "Gold Coast", "Hobart"] },
    { name: "Austria", provinces: ["Burgenland", "Kärnten", "Niederösterreich", "Oberösterreich", "Salzburg", "Steiermark", "Tirol", "Vorarlberg", "Wien"], cities: ["Vienna", "Salzburg", "Innsbruck", "Graz", "Linz", "Hallstatt"] },
    { name: "Azerbaijan", provinces: [] },
    { name: "Bahamas", provinces: [] },
    { name: "Bahrain", provinces: [] },
    { name: "Bangladesh", provinces: [] },
    { name: "Barbados", provinces: [] },
    { name: "Belarus", provinces: [] },
    { name: "Belgium", provinces: ["Flanders", "Wallonia", "Brussels-Capital Region"], cities: ["Brussels", "Antwerp", "Bruges", "Ghent", "Liège"] },
    { name: "Belize", provinces: [] },
    { name: "Benin", provinces: [] },
    { name: "Bhutan", provinces: [] },
    { name: "Bolivia", provinces: [], cities: ["La Paz", "Sucre", "Uyuni", "Santa Cruz de la Sierra"] },
    { name: "Bosnia and Herzegovina", provinces: [], cities: ["Sarajevo", "Mostar", "Banja Luka"] },
    { name: "Botswana", provinces: [] },
    { name: "Brazil", provinces: ["Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins"], cities: ["Rio de Janeiro", "São Paulo", "Salvador", "Brasília", "Florianópolis"] },
    { name: "Brunei", provinces: [] },
    { name: "Bulgaria", provinces: [], cities: ["Sofia", "Plovdiv", "Varna", "Bansko"] },
    { name: "Burkina Faso", provinces: [] },
    { name: "Burundi", provinces: [] },
    { name: "Cabo Verde", provinces: [] },
    { name: "Cambodia", provinces: [], cities: ["Phnom Penh", "Siem Reap", "Sihanoukville"] },
    { name: "Cameroon", provinces: [] },
    { name: "Canada", provinces: ["Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Nova Scotia", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", "Northwest Territories", "Nunavut", "Yukon"], cities: ["Toronto", "Vancouver", "Montreal", "Quebec City", "Ottawa", "Calgary", "Banff"] },
    { name: "Central African Republic", provinces: [] },
    { name: "Chad", provinces: [] },
    { name: "Chile", provinces: [], cities: ["Santiago", "Valparaíso", "San Pedro de Atacama", "Punta Arenas"] },
    { name: "China", provinces: ["Beijing", "Shanghai", "Tianjin", "Chongqing", "Hebei", "Shanxi", "Liaoning", "Jilin", "Heilongjiang", "Jiangsu", "Zhejiang", "Anhui", "Fujian", "Jiangxi", "Shandong", "Henan", "Hubei", "Hunan", "Guangdong", "Hainan", "Sichuan", "Guizhou", "Yunnan", "Shaanxi", "Gansu", "Qinghai", "Guangxi", "Inner Mongolia", "Ningxia", "Xinjiang", "Tibet", "Hong Kong", "Macau"], cities: ["Beijing", "Shanghai", "Hong Kong", "Xi'an", "Guangzhou", "Chengdu", "Shenzhen"] },
    { name: "Colombia", provinces: [], cities: ["Bogotá", "Medellín", "Cartagena", "Cali"] },
    { name: "Comoros", provinces: [] },
    { name: "Congo (Republic of the)", provinces: [] },
    { name: "Congo (Democratic Republic of the)", provinces: [] },
    { name: "Costa Rica", provinces: [], cities: ["San José", "Tamarindo", "Manuel Antonio", "Monteverde"] },
    { name: "Croatia", provinces: ["Zagreb County", "Krapina-Zagorje", "Sisak-Moslavina", "Karlovac", "Varaždin", "Koprivnica-Križevci", "Bjelovar-Bilogora", "Primorje-Gorski Kotar", "Lika-Senj", "Virovitica-Podravina", "Požega-Slavonia", "Brod-Posavina", "Zadar", "Osijek-Baranja", "Šibenik-Knin", "Vukovar-Syrmia", "Split-Dalmatia", "Istria", "Dubrovnik-Neretva", "Međimurje", "City of Zagreb"], cities: ["Zagreb", "Split", "Dubrovnik", "Zadar", "Rovinj", "Pula"] },
    { name: "Cuba", provinces: [], cities: ["Havana", "Varadero", "Trinidad", "Santiago de Cuba"] },
    { name: "Cyprus", provinces: [], cities: ["Nicosia", "Limassol", "Paphos", "Ayia Napa"] },
    { name: "Czechia", provinces: ["Prague", "Central Bohemian", "South Bohemian", "Plzeň", "Karlovy Vary", "Ústí nad Labem", "Liberec", "Hradec Králové", "Pardubice", "Olomouc", "Moravian-Silesian", "South Moravian", "Zlín", "Vysočina"], cities: ["Prague", "Brno", "Český Krumlov", "Karlovy Vary"] },
    { name: "Denmark", provinces: ["Capital Region", "Zealand", "Southern Denmark", "Central Denmark", "North Denmark"], cities: ["Copenhagen", "Aarhus", "Odense", "Aalborg"] },
    { name: "Djibouti", provinces: [] },
    { name: "Dominica", provinces: [] },
    { name: "Dominican Republic", provinces: [], cities: ["Santo Domingo", "Punta Cana", "Puerto Plata"] },
    { name: "Ecuador", provinces: [], cities: ["Quito", "Guayaquil", "Galápagos Islands", "Cuenca"] },
    { name: "Egypt", provinces: ["Cairo", "Giza", "Alexandria", "Luxor", "Aswan", "Red Sea", "South Sinai", "Matrouh"], cities: ["Cairo", "Luxor", "Aswan", "Sharm El Sheikh", "Hurghada", "Alexandria"] },
    { name: "El Salvador", provinces: [] },
    { name: "Equatorial Guinea", provinces: [] },
    { name: "Eritrea", provinces: [] },
    { name: "Estonia", provinces: [], cities: ["Tallinn", "Tartu"] },
    { name: "Eswatini", provinces: [] },
    { name: "Ethiopia", provinces: [] },
    { name: "Fiji", provinces: [] },
    { name: "Finland", provinces: ["Lapland", "North Ostrobothnia", "Kainuu", "North Karelia", "North Savo", "South Savo", "South Ostrobothnia", "Ostrobothnia", "Central Ostrobothnia", "Pirkanmaa", "Satakunta", "Central Finland", "Päijänne Tavastia", "Tavastia Proper", "South Karelia", "Kymenlaakso", "Uusimaa", "Southwest Finland", "Åland"], cities: ["Helsinki", "Tampere", "Turku", "Rovaniemi"] },
    { name: "France", provinces: ["Auvergne-Rhône-Alpes", "Bourgogne-Franche-Comté", "Bretagne", "Centre-Val de Loire", "Corse", "Grand Est", "Hauts-de-France", "Île-de-France", "Normandie", "Nouvelle-Aquitaine", "Occitanie", "Pays de la Loire", "Provence-Alpes-Côte d'Azur", "Guadeloupe", "Martinique", "Guyane", "La Réunion", "Mayotte"], cities: ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille", "Rennes", "Annecy"] },
    { name: "Gabon", provinces: [] },
    { name: "Gambia", provinces: [] },
    { name: "Georgia", provinces: [], cities: ["Tbilisi", "Batumi", "Kazbegi"] },
    { name: "Germany", provinces: ["Baden-Württemberg", "Bayern", "Berlin", "Brandenburg", "Bremen", "Hamburg", "Hessen", "Mecklenburg-Vorpommern", "Niedersachsen", "Nordrhein-Westfalen", "Rheinland-Pfalz", "Saarland", "Sachsen", "Sachsen-Anhalt", "Schleswig-Holstein", "Thüringen"], cities: ["Berlin", "Munich", "Hamburg", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Dresden", "Leipzig", "Nuremberg"] },
    { name: "Ghana", provinces: [] },
    { name: "Greece", provinces: ["Attica", "Central Greece", "Central Macedonia", "Crete", "Eastern Macedonia and Thrace", "Epirus", "Ionian Islands", "North Aegean", "Peloponnese", "South Aegean", "Thessaly", "Western Greece", "Western Macedonia"], cities: ["Athens", "Thessaloniki", "Heraklion", "Santorini", "Mykonos", "Rhodes"] },
    { name: "Grenada", provinces: [] },
    { name: "Guatemala", provinces: [], cities: ["Guatemala City", "Antigua Guatemala", "Lake Atitlán"] },
    { name: "Guinea", provinces: [] },
    { name: "Guinea-Bissau", provinces: [] },
    { name: "Guyana", provinces: [] },
    { name: "Haiti", provinces: [] },
    { name: "Honduras", provinces: [] },
    { name: "Hungary", provinces: ["Bács-Kiskun", "Baranya", "Békés", "Borsod-Abaúj-Zemplén", "Csongrád-Csanád", "Fejér", "Győr-Moson-Sopron", "Hajdú-Bihar", "Heves", "Jász-Nagykun-Szolnok", "Komárom-Esztergom", "Nógrád", "Pest", "Somogy", "Szabolcs-Szatmár-Bereg", "Tolna", "Vas", "Veszprém", "Zala", "Budapest"], cities: ["Budapest", "Debrecen", "Szeged", "Pécs"] },
    { name: "Iceland", provinces: ["Capital Region", "Southern Peninsula", "Western Region", "Westfjords", "Northwestern Region", "Northeastern Region", "Eastern Region", "Southern Region"], cities: ["Reykjavik", "Akureyri"] },
    { name: "India", provinces: ["Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"], cities: ["Delhi", "Mumbai", "Jaipur", "Goa", "Agra", "Varanasi", "Bangalore"] },
    { name: "Indonesia", provinces: ["Jakarta", "Bali", "West Java", "East Java", "Yogyakarta", "North Sumatra", "South Sulawesi"], cities: ["Jakarta", "Denpasar (Bali)", "Yogyakarta", "Bandung", "Surabaya"] },
    { name: "Iran", provinces: [] },
    { name: "Iraq", provinces: [] },
    { name: "Ireland", provinces: ["Carlow", "Cavan", "Clare", "Cork", "Donegal", "Dublin", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Waterford", "Westmeath", "Wexford", "Wicklow"], cities: ["Dublin", "Cork", "Galway", "Limerick", "Killarney"] },
    { name: "Israel", provinces: [], cities: ["Jerusalem", "Tel Aviv", "Haifa", "Eilat"] },
    {
      name: "Italy",
      provinces: [
        "Piemonte", "Valle d'Aosta", "Liguria", "Lombardia", "Trentino-Alto Adige",
        "Veneto", "Friuli-Venezia Giulia", "Emilia-Romagna", "Toscana", "Umbria",
        "Marche", "Lazio", "Abruzzo", "Molise", "Campania", "Puglia",
        "Basilicata", "Calabria", "Sicilia", "Sardegna"
      ],
      cities: ["Roma", "Milano", "Napoli", "Torino", "Palermo", "Genova", "Bologna", "Firenze", "Bari", "Catania", "Venezia", "Verona", "Trento", "Bolzano", "Canazei", "Merano", "Cortina d'Ampezzo"]
    },
    { name: "Ivory Coast", provinces: [] },
    { name: "Jamaica", provinces: [] },
    { name: "Japan", provinces: ["Hokkaido", "Aomori", "Iwate", "Miyagi", "Akita", "Yamagata", "Fukushima", "Ibaraki", "Tochigi", "Gunma", "Saitama", "Chiba", "Tokyo", "Kanagawa", "Niigata", "Toyama", "Ishikawa", "Fukui", "Yamanashi", "Nagano", "Gifu", "Shizuoka", "Aichi", "Mie", "Shiga", "Kyoto", "Osaka", "Hyogo", "Nara", "Wakayama", "Tottori", "Shimane", "Okayama", "Hiroshima", "Yamaguchi", "Tokushima", "Kagawa", "Ehime", "Kochi", "Fukuoka", "Saga", "Nagasaki", "Kumamoto", "Oita", "Miyazaki", "Kagoshima", "Okinawa"], cities: ["Tokyo", "Osaka", "Kyoto", "Hiroshima", "Sapporo", "Nagoya", "Yokohama", "Nara"] },
    { name: "Jordan", provinces: [], cities: ["Amman", "Petra", "Wadi Rum", "Aqaba"] },
    { name: "Kazakhstan", provinces: [] },
    { name: "Kenya", provinces: [], cities: ["Nairobi", "Mombasa", "Maasai Mara"] },
    { name: "Kiribati", provinces: [] },
    { name: "Kosovo", provinces: [], cities: ["Pristina", "Prizren"] },
    { name: "Kuwait", provinces: [] },
    { name: "Kyrgyzstan", provinces: [] },
    { name: "Laos", provinces: [], cities: ["Vientiane", "Luang Prabang"] },
    { name: "Latvia", provinces: [], cities: ["Riga"] },
    { name: "Lebanon", provinces: [], cities: ["Beirut", "Byblos"] },
    { name: "Lesotho", provinces: [] },
    { name: "Liberia", provinces: [] },
    { name: "Libya", provinces: [] },
    { name: "Liechtenstein", provinces: [], cities: ["Vaduz"] },
    { name: "Lithuania", provinces: [], cities: ["Vilnius", "Kaunas"] },
    { name: "Luxembourg", provinces: [], cities: ["Luxembourg City"] },
    { name: "Madagascar", provinces: [] },
    { name: "Malawi", provinces: [] },
    { name: "Malaysia", provinces: [], cities: ["Kuala Lumpur", "Penang", "Langkawi", "Malacca"] },
    { name: "Maldives", provinces: [], cities: ["Malé"] },
    { name: "Mali", provinces: [] },
    { name: "Malta", provinces: [], cities: ["Valletta", "Sliema", "Mdina"] },
    { name: "Marshall Islands", provinces: [] },
    { name: "Mauritania", provinces: [] },
    { name: "Mauritius", provinces: [], cities: ["Port Louis"] },
    { name: "Mexico", provinces: ["Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Coahuila", "Colima", "Mexico City", "Durango", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Mexico State", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas"], cities: ["Mexico City", "Cancún", "Guadalajara", "Playa del Carmen", "Tulum", "Oaxaca City"] },
    { name: "Micronesia", provinces: [] },
    { name: "Moldova", provinces: [] },
    { name: "Monaco", provinces: [], cities: ["Monte Carlo"] },
    { name: "Mongolia", provinces: [], cities: ["Ulaanbaatar"] },
    { name: "Montenegro", provinces: [], cities: ["Kotor", "Budva", "Podgorica"] },
    { name: "Morocco", provinces: ["Tanger-Tétouan-Al Hoceïma", "Oriental", "Fès-Meknès", "Rabat-Salé-Kénitra", "Béni Mellal-Khénifra", "Casablanca-Settat", "Marrakech-Safi", "Drâa-Tafilalet", "Souss-Massa", "Guelmim-Oued Noun", "Laâyoune-Sakia El Hamra", "Dakhla-Oued Ed-Dahab"], cities: ["Marrakech", "Casablanca", "Fes", "Rabat", "Chefchaouen", "Essaouira"] },
    { name: "Mozambique", provinces: [] },
    { name: "Myanmar", provinces: [] },
    { name: "Namibia", provinces: [] },
    { name: "Nauru", provinces: [] },
    { name: "Nepal", provinces: [], cities: ["Kathmandu", "Pokhara"] },
    { name: "Netherlands", provinces: ["Drenthe", "Flevoland", "Friesland", "Gelderland", "Groningen", "Limburg", "Noord-Brabant", "Noord-Holland", "Overijssel", "Utrecht", "Zeeland", "Zuid-Holland"], cities: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"] },
    { name: "New Zealand", provinces: ["Auckland", "Bay of Plenty", "Canterbury", "Gisborne", "Hawke's Bay", "Manawatū-Whanganui", "Marlborough", "Nelson", "Northland", "Otago", "Southland", "Taranaki", "Tasman", "Waikato", "Wellington", "West Coast"], cities: ["Auckland", "Wellington", "Queenstown", "Christchurch", "Rotorua"] },
    { name: "Nicaragua", provinces: [] },
    { name: "Niger", provinces: [] },
    { name: "Nigeria", provinces: [] },
    { name: "North Korea", provinces: [] },
    { name: "North Macedonia", provinces: [], cities: ["Skopje", "Ohrid"] },
    { name: "Norway", provinces: ["Oslo", "Rogaland", "Møre og Romsdal", "Nordland", "Østfold", "Akershus", "Buskerud", "Innlandet", "Vestfold", "Telemark", "Agder", "Vestland", "Trøndelag", "Troms", "Finnmark"], cities: ["Oslo", "Bergen", "Trondheim", "Tromsø"] },
    { name: "Oman", provinces: [] },
    { name: "Pakistan", provinces: [] },
    { name: "Palau", provinces: [] },
    { name: "Palestine", provinces: [] },
    { name: "Panama", provinces: [], cities: ["Panama City", "Bocas del Toro"] },
    { name: "Papua New Guinea", provinces: [] },
    { name: "Paraguay", provinces: [] },
    { name: "Peru", provinces: [], cities: ["Lima", "Cusco", "Machu Picchu (Aguas Calientes)", "Arequipa"] },
    { name: "Philippines", provinces: ["National Capital Region (Manila)", "Cebu (Central Visayas)", "Davao Region", "Palawan (Mimaropa)", "Ilocos Region", "Bicol Region"], cities: ["Manila", "Cebu City", "Davao", "Boracay (Aklan)", "Palawan"] },
    { name: "Poland", provinces: ["Greater Poland", "Kuyavian-Pomeranian", "Lesser Poland", "Łódź", "Lower Silesian", "Lublin", "Lubusz", "Masovian", "Opole", "Podlaskie", "Pomeranian", "Silesian", "Subcarpathian", "Świętokrzyskie", "Warmian-Masurian", "West Pomeranian"], cities: ["Warsaw", "Kraków", "Gdańsk", "Wrocław", "Poznań"] },
    { name: "Portugal", provinces: ["Aveiro", "Beja", "Braga", "Bragança", "Castelo Branco", "Coimbra", "Évora", "Faro", "Guarda", "Leiria", "Lisboa", "Portalegre", "Porto", "Santarém", "Setúbal", "Viana do Castelo", "Vila Real", "Viseu", "Açores", "Madeira"], cities: ["Lisbon", "Porto", "Faro", "Coimbra", "Braga", "Sintra"] },
    { name: "Qatar", provinces: [], cities: ["Doha"] },
    { name: "Romania", provinces: [], cities: ["Bucharest", "Brașov", "Sibiu", "Cluj-Napoca"] },
    { name: "Russia", provinces: [], cities: ["Moscow", "Saint Petersburg"] },
    { name: "Rwanda", provinces: [] },
    { name: "Saint Kitts and Nevis", provinces: [] },
    { name: "Saint Lucia", provinces: [] },
    { name: "Saint Vincent and the Grenadines", provinces: [] },
    { name: "Samoa", provinces: [] },
    { name: "San Marino", provinces: [], cities: ["City of San Marino"] },
    { name: "Sao Tome and Principe", provinces: [] },
    { name: "Saudi Arabia", provinces: [], cities: ["Riyadh", "Jeddah", "Mecca", "AlUla"] },
    { name: "Senegal", provinces: [] },
    { name: "Serbia", provinces: [], cities: ["Belgrade", "Novi Sad"] },
    { name: "Seychelles", provinces: [] },
    { name: "Sierra Leone", provinces: [] },
    { name: "Singapore", provinces: [], cities: ["Singapore"] },
    { name: "Slovakia", provinces: [], cities: ["Bratislava", "Košice"] },
    { name: "Slovenia", provinces: ["Gorenjska", "Goriška", "Jugovzhodna Slovenija", "Koroška", "Notranjsko-kraška", "Obalno-kraška", "Osrednjeslovenska", "Podravska", "Pomurska", "Posavska", "Savinjska", "Zasavska"], cities: ["Ljubljana", "Bled", "Piran"] },
    { name: "Solomon Islands", provinces: [] },
    { name: "Somalia", provinces: [] },
    { name: "South Africa", provinces: ["Eastern Cape", "Free State", "Gauteng", "KwaZulu-Natal", "Limpopo", "Mpumalanga", "North West", "Northern Cape", "Western Cape"], cities: ["Cape Town", "Johannesburg", "Durban", "Pretoria"] },
    { name: "South Korea", provinces: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Ulsan", "Sejong", "Gyeonggi", "Gangwon", "North Chungcheong", "South Chungcheong", "North Jeolla", "South Jeolla", "North Gyeongsang", "South Gyeongsang", "Jeju"], cities: ["Seoul", "Busan", "Jeju", "Incheon", "Gyeongju"] },
    { name: "South Sudan", provinces: [] },
    { name: "Spain", provinces: ["Andalucía", "Aragón", "Asturias", "Baleares", "País Vasco", "Canarias", "Cantabria", "Castilla y León", "Castilla-La Mancha", "Cataluña", "Madrid", "Extremadura", "Galicia", "La Rioja", "Navarra", "Murcia", "Comunidad Valenciana", "Ceuta", "Melilla"], cities: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Bilbao", "Málaga", "Zaragoza", "Granada", "San Sebastián", "Palma de Mallorca"] },
    { name: "Sri Lanka", provinces: [], cities: ["Colombo", "Kandy", "Galle", "Ella"] },
    { name: "Sudan", provinces: [] },
    { name: "Suriname", provinces: [] },
    { name: "Sweden", provinces: ["Stockholm", "Uppsala", "Södermanland", "Östergötland", "Jönköping", "Kronoberg", "Kalmar", "Gotland", "Blekinge", "Skåne", "Halland", "Västra Götaland", "Värmland", "Örebro", "Västmanland", "Dalarna", "Gävleborg", "Västernorrland", "Jämtland", "Västerbotten", "Norrbotten"], cities: ["Stockholm", "Gothenburg", "Malmö", "Uppsala"] },
    { name: "Switzerland", provinces: ["Zürich", "Bern", "Luzern", "Uri", "Schwyz", "Obwalden", "Nidwalden", "Glarus", "Zug", "Fribourg", "Solothurn", "Basel-Stadt", "Basel-Landschaft", "Schaffhausen", "Appenzell Ausserrhoden", "Appenzell Innerrhoden", "St. Gallen", "Graubünden", "Aargau", "Thurgau", "Ticino", "Vaud", "Valais", "Neuchâtel", "Genève", "Jura"], cities: ["Zürich", "Geneva", "Basel", "Bern", "Lausanne", "Lucerne", "Lugano", "Interlaken", "Zermatt"] },
    { name: "Syria", provinces: [] },
    { name: "Taiwan", provinces: [], cities: ["Taipei", "Kaohsiung", "Taichung"] },
    { name: "Tajikistan", provinces: [] },
    { name: "Tanzania", provinces: [], cities: ["Zanzibar", "Arusha", "Dar es Salaam"] },
    { name: "Thailand", provinces: [], cities: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Krabi", "Ayutthaya"] },
    { name: "Timor-Leste", provinces: [] },
    { name: "Togo", provinces: [] },
    { name: "Tonga", provinces: [] },
    { name: "Trinidad and Tobago", provinces: [] },
    { name: "Tunisia", provinces: [], cities: ["Tunis", "Sidi Bou Said", "Djerba"] },
    { name: "Turkey", provinces: [], cities: ["Istanbul", "Ankara", "Izmir", "Antalya", "Cappadocia (Nevşehir)", "Bodrum", "Pamukkale (Denizli)"] },
    { name: "Turkmenistan", provinces: [] },
    { name: "Tuvalu", provinces: [] },
    { name: "Uganda", provinces: [] },
    { name: "Ukraine", provinces: [], cities: ["Kyiv", "Lviv", "Odesa"] },
    { name: "United Arab Emirates", provinces: ["Abu Dhabi", "Dubai", "Sharjah", "Ajman", "Umm Al Quwain", "Fujairah", "Ras Al Khaimah"], cities: ["Dubai", "Abu Dhabi", "Sharjah"] },
    { name: "United Kingdom", provinces: ["England", "Scotland", "Wales", "Northern Ireland"], cities: ["London", "Edinburgh", "Manchester", "Liverpool", "Glasgow", "Cardiff", "Belfast", "Oxford", "Bath", "York"] },
    { name: "United States", provinces: ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"], cities: ["New York City", "Los Angeles", "Chicago", "San Francisco", "Las Vegas", "Miami", "Seattle", "Boston", "Washington D.C.", "New Orleans"] },
    { name: "Uruguay", provinces: [], cities: ["Montevideo", "Punta del Este", "Colonia del Sacramento"] },
    { name: "Uzbekistan", provinces: [], cities: ["Tashkent", "Samarkand", "Bukhara"] },
    { name: "Vanuatu", provinces: [] },
    { name: "Vatican City", provinces: [], cities: ["Vatican City"] },
    { name: "Venezuela", provinces: [] },
    { name: "Vietnam", provinces: [], cities: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hai Phong", "Ha Long Bay (Quang Ninh)", "Nha Trang (Khanh Hoa)", "Da Lat (Lam Dong)", "Hue", "Hoi An (Quang Nam)", "Ninh Binh", "Sapa (Lao Cai)"] },
    { name: "Yemen", provinces: [] },
    { name: "Zambia", provinces: [] },
    { name: "Zimbabwe", provinces: [] }
  ]
};
